export const DEPOSIT_DIALOG_SHOW = 'DEPOSIT_DIALOG_SHOW';
export const DEPOSIT_DIALOG_HIDE = 'DEPOSIT_DIALOG_HIDE';

export const WITHDRAW_DIALOG_SHOW = 'WITHDRAW_DIALOG_SHOW';
export const WITHDRAW_DIALOG_HIDE = 'WITHDRAW_DIALOG_HIDE';

export const AMOUNT_VALUE_SET = 'AMOUNT_VALUE_SET';

export const CONNECT_IBC_ACCOUNT_IN_PROGRESS = 'CONNECT_IBC_ACCOUNT_IN_PROGRESS';
export const CONNECT_IBC_ACCOUNT_SUCCESS = 'CONNECT_IBC_ACCOUNT_SUCCESS';
export const CONNECT_IBC_ACCOUNT_ERROR = 'CONNECT_IBC_ACCOUNT_ERROR';

export const IBC_BALANCE_FETCH_IN_PROGRESS = 'IBC_BALANCE_FETCH_IN_PROGRESS';
export const IBC_BALANCE_FETCH_SUCCESS = 'IBC_BALANCE_FETCH_SUCCESS';
export const IBC_BALANCE_FETCH_ERROR = 'IBC_BALANCE_FETCH_ERROR';

export const AMINO_SIGN_IBC_TX_IN_PROGRESS = 'AMINO_SIGN_IBC_TX_IN_PROGRESS';
export const AMINO_SIGN_IBC_TX_SUCCESS = 'AMINO_SIGN_IBC_TX_SUCCESS';
export const AMINO_SIGN_IBC_TX_ERROR = 'AMINO_SIGN_IBC_TX_ERROR';

export const TIMEOUT_HEIGHT_FETCH_IN_PROGRESS = 'TIMEOUT_HEIGHT_FETCH_IN_PROGRESS';
export const TIMEOUT_HEIGHT_FETCH_SUCCESS = 'TIMEOUT_HEIGHT_FETCH_SUCCESS';
export const TIMEOUT_HEIGHT_FETCH_ERROR = 'TIMEOUT_HEIGHT_FETCH_ERROR';

export const FAUCET_DIALOG_SHOW = 'FAUCET_DIALOG_SHOW';
export const FAUCET_DIALOG_HIDE = 'FAUCET_DIALOG_HIDE';

export const FAUCET_SUCCESS_SET = 'FAUCET_SUCCESS_SET';

export const FAUCET_BALANCE_ADD_IN_PROGRESS = 'FAUCET_BALANCE_ADD_IN_PROGRESS';
export const FAUCET_BALANCE_ADD_SUCCESS = 'FAUCET_BALANCE_ADD_SUCCESS';
export const FAUCET_BALANCE_ADD_ERROR = 'FAUCET_BALANCE_ADD_ERROR';

export const IBC_BALANCE_LIST_FETCH_IN_PROGRESS = 'IBC_BALANCE_LIST_FETCH_IN_PROGRESS';
export const IBC_BALANCE_LIST_FETCH_SUCCESS = 'IBC_BALANCE_LIST_FETCH_SUCCESS';
export const IBC_BALANCE_LIST_FETCH_ERROR = 'IBC_BALANCE_LIST_FETCH_ERROR';
