export const STREAMS_TAB_SET = 'STREAMS_TAB_SET';

export const TO_ADDRESS_SET = 'TO_ADDRESS_SET';
export const TYPE_TAB_SET = 'TYPE_TAB_SET';
export const AMOUNT_SET = 'AMOUNT_SET';
export const TOKEN_SET = 'TOKEN_SET';
export const END_DATE_SET = 'END_DATE_SET';

export const OUTGOING_STREAMS_FETCH_IN_PROGRESS = 'OUTGOING_STREAMS_FETCH_IN_PROGRESS';
export const OUTGOING_STREAMS_FETCH_SUCCESS = 'OUTGOING_STREAMS_FETCH_SUCCESS';
export const OUTGOING_STREAMS_FETCH_ERROR = 'OUTGOING_STREAMS_FETCH_ERROR';

export const INCOMING_STREAMS_FETCH_IN_PROGRESS = 'INCOMING_STREAMS_FETCH_IN_PROGRESS';
export const INCOMING_STREAMS_FETCH_SUCCESS = 'INCOMING_STREAMS_FETCH_SUCCESS';
export const INCOMING_STREAMS_FETCH_ERROR = 'INCOMING_STREAMS_FETCH_ERROR';
